config/routes.rb
Rails.application.routes.draw do
  # кастомный экшн у ресурса railway_stations
  # указываем, что у нас есть дополнительный экш, где перед ним
  # пишем HTTP метод, при помощи которого мы хотим обращаться к нашему экшену
  # после запятой задаем вопрос: этот экшн применяется к конкретному объекту или коллекции?
  # URL должен содержать id объекта или нет?
  # если коллекция, пишем on: :collection. если конкретный - on: :member
  #
  # здесь важно правильно указать HTTP-метод:
  # если получение данных без изменения - GET
  # создание чего-то нового или какая-то неконкретная отправка данных на сервер - POST
  # изменение - PATCH/PUT
  # удаление - DELETE
  resources :railway_stations do
    put :update_position, on: :member
  end

  resources :trains do
    # shallow: true - эта опция укажет, что родительский объект @train нужен только для
    # экшнов index, create, new. Все остальные его не требуют. Можем в этом убедиться, посмотрев
    # роутинг командой rails routes
    resources :carriages, shallow: true
  end

  resources :routes

  # когда мы пишем resource(в единственном числе), мы создаем singular resource(единственный ресурс)
  # rails routes покажет, что у singular resource в роутинге нет метода index, что логично -
  # - раз ресурс в одном экземпляре, значит нет списка этих ресурсов
  #
  # У любого ресурса можно указать, какие экшны нам нужны - опция only для определенных экшнов,
  # опция except - все, кроме.
  resource :search, only: %i[new show edit]

  get 'welcome/index'
  get "/trains", to: "trains#index"
  get "/trains/:id", to: "trains#show"

  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/train.rb
class Train < ApplicationRecord
  # belongs_to всегд принимает название модели в единственном числе
  # модель Train связана с одной current_station - теперь рельсы это знают
  # мы можем получить ту станцию, на которой сейчас находится поезд, через
  # метод current_station
  #
  # вся магия происхоидт из соглашения по именам:
  # указаов вот это, рельсы знают, что в нашей таблице trains
  # должно быть поле current_station_id и должно ссылаться на таблицу
  # railway_stations.
  #
  # Если мы будем обращаться на уровне моделей к этой ассоциации, то рельсы будут знать,
  # что нужно взять из таблицы railway_stations некую запись, связанную по id в таблице
  # trains, создать модель railway_station для этой записи(строки) и вернуть конкретную модель,
  # конкретный объект railway_station.
  #
  # модель у нас будет другая: class_name: 'ИмяАссоциации'. Теперь рельсы будут знать, что в
  # качестве таблицы нужно использовать raylway_stations, а в качестве модели класс RailwayStation.
  # желательно в таких случаях указывть в явном виде foreign_key: :название_внешнего_ключа
  #
  # поле - внешний ключ для таблицы должен называться так же, как и таблица,
  # только в "единственном_числе_id"
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  # Нам не нужно добавлять классы моделей, которые наследуются от Carriage, поскольку мы используем
  # Single Table Inheritance
  has_many :carriages

  validates :number, presence: true
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  # метод, который мы выполняем до того, как выполним перечисленные методы в [....]
  # указываем опцию only: и массив символов, в котором указаны те экшены, перед
  # которыми будет выполняться метод set_train
  before_action :set_train, only: %i[show edit update destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: "Поезд успешно создан."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @train.update(train_params)
      redirect_to @train, notice: "Поезд успешно изменен."
    else
      render :edit
    end
  end

  def destroy
    @train.destroy

    redirect_to trains_path, status: :see_other
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/views/trains/_form.html.erb
<%= form_with(model: @train) do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div>
    <%= form.label 'Номер', style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :current_station, 'Текущая станция' %>
    <!-- collection_select принимает 4 аргумента:
     1) то поле, в которое у нас будет устанавливаться связь (какое поле мы будем связывать в объекте train)
     2) указывается выборка - коллекция тех объектов, из которых мы можем выбирать (список всех моделей)
     3) что у нас будет значением в списке (какое из каждых этих объектов значение будет отправлено в форме
     на сервер)
     4) что будет значением в качестве параметра (какое из полей будет использоваться для отображения
     этого списка пользователю)
     -->
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div>
    <%= form.submit "#{ @train.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to "Изменить", edit_train_path(train) %></td>
  <td><%= link_to "Удалить", train, data: {
      turbo_method: :delete,
      turbo_confirm: "Вы уверены?"
  } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render "form", resource: @train %>

<br>

<div>
  <%= link_to "Назад к поездам", trains_path %>
</div>

app/views/trains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Поезда</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <!-- анонимный паршэл: когда Rails автоматически, на основе соглашения
    об именах объектов и паршэлов, определяет какой конкретно паршэл нужно отрендерить и,
    если нужно, то рендерит коллекцию. Анон.паршэл находится: views/trains/_train.html.erb

    Если мы в render передадим коллекцию определенного типа, он их автоматически
    переберет через each, и для каждого объекта сделает рендеринг соответствующего шаблона

    Если у нас ситуация, что для одиночного объекта у нас один код, а для коллекции - другой,
    тогда можно сделать паршэл во множественном числе _trains.html.erb, и если мы передадим коллекцию
    в render, то будет рендериться шаблон _trains. Если данного шаблона нет, то для каждого объекта
    внутри коллекции будет рендериться шаблон для одного объекта(_train)  -->
    <%= render @trains %>
  </tbody>
</table>

<div><br>
  <%= link_to 'На главную', welcome_index_path, method: :get %> |
  <%= link_to 'Новый поезд', new_train_path %>
</div>


app/views/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form', resource: @train %>

<p><%= link_to 'Назад', trains_path %></p>

app/views/trains/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>На станции:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <% end %>
</p>

<p>
  <strong>Вагоны:</strong>
  <ul>
    <% @train.carriages.each do |carr| %>
      <!-- Так как ресурс вложенный, мы должны указать в массиве сначала родительский @train,
       затем вложенный carr. Если в роутинге включим опцию shallow: true,
       то исключаем родительский @train из массива -->
    <li><%= link_to "Вагон №#{carr.number}", carr %></li>
    <% end %>
  </ul>
</p>

<tr>
    <!-- так как carriage - вложенный ресурс, хэлперу new_train_carriage_path мы обязаны
    указать родительский объект, в нашем случае @train -->
  <td><%= link_to 'Добавить вагон', new_train_carriage_path(@train) %> |</td>
  <td><%= link_to "Изменить", edit_train_path(@train) %> |</td>
  <td><%= link_to "Удалить", train_path(@train), data: {
      turbo_method: :delete,
      turbo_confirm: "Вы уверены?"
  } %></td>
</tr>

<div><br>
  <%= link_to 'Назад к поездам', trains_path, method: :get %>
</div>