config/routes.rb
Rails.application.routes.draw do
  # кастомный экшн у ресурса railway_stations
  # указываем, что у нас есть дополнительный экш, где перед ним
  # пишем HTTP метод, при помощи которого мы хотим обращаться к нашему экшену
  # после запятой задаем вопрос: этот экшн применяется к конкретному объекту или коллекции?
  # URL должен содержать id объекта или нет?
  # если коллекция, пишем on: :collection. если конкретный - on: :member
  #
  # здесь важно правильно указать HTTP-метод:
  # если получение данных без изменения - GET
  # создание чего-то нового или какая-то неконкретная отправка данных на сервер - POST
  # изменение - PATCH/PUT
  # удаление - DELETE
  resources :railway_stations do
    put :update_position, on: :member
  end

  resources :trains do
    # shallow: true - эта опция укажет, что родительский объект @train нужен только для
    # экшнов index, create, new. Все остальные его не требуют. Можем в этом убедиться, посмотрев
    # роутинг командой rails routes
    resources :carriages, shallow: true
  end

  resources :routes

  # когда мы пишем resource(в единственном числе), мы создаем singular resource(единственный ресурс)
  # rails routes покажет, что у singular resource в роутинге нет метода index, что логично -
  # - раз ресурс в одном экземпляре, значит нет списка этих ресурсов
  #
  # У любого ресурса можно указать, какие экшны нам нужны - опция only для определенных экшнов,
  # опция except - все, кроме.
  resource :search, only: %i[new show edit]

  get 'welcome/index'
  get "/trains", to: "trains#index"
  get "/trains/:id", to: "trains#show"

  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  # чтобы получать список всех поездов на станции
  # has_many :trains указывает, что станция имеет множество поездов
  #
  # где писать единственное число, а где множественное, запоминать не нужно, надо
  # просто понять суть: если объект принадлежит к другому объекту - единственное число,
  # если объект принадлежит к множеству других объектов - во множественном.
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  # scope :ordered - выводит упорядочено станции
  # нужно применить объединение таблиц: нашей r_s и r_s_r, поле position находится в таблице r_s_r,
  # и не смотря на то, что у нас есть связь has_many, фактически, эти таблицы не объединены
  # поэтому наш нужен запрос joins - объединить с таблицей, затем order - нужно указать полное
  # название таблицы и поле. В конце добавим метод uniq для исключения(убрать) повторяющихся станций
  scope :ordered, -> { joins(:railway_stations_routes).order('railway_stations_routes.position').uniq }

  validates :title, presence: true

  # метод принимает route - объект маршрута, position
  # дальше нам нужно найти через ассоциацию railway_stations_routes нужную запись в таблице
  # присвоим ее в локальную переменную и назовем station_route, а внутри переменной обращаемся
  # к ассоциации railway_station_routes. Так как мы работаем внутри конкретного объекта станции,
  # это означает, что railway_stations_routes, вызванный здесь, вернет нам только те записи, которые
  # связаны с нашей конкретной станцией, но станция может быть в разных маррутах, поэтому
  # нужен доп.фильтр where - фильтр по маршруту.
  # Мы найдем среди тех записей в таблице r_s_r, которые принадлежат конкретной станции, еще и те, которые
  # принадлежат конкретному переданному маршруту.
  # Но where возвращает не сам объект, а relation - связь. Чтобы получить сам объект, нужно вызвать first
  # (поскольку мы предполагаем, что он должен быть один)
  #
  # дальше у полученного объекта вызываем update, и обновляем поле position
  # НО! Запрос station_route = railway_stations_routes.where(route: route).first не гарантированно
  # вернет нам объект: если записи нет, то там будет nil, а вызвав update у nil будет ошибка
  # поэтому делаем доп.проверку if station_route(если у нас присутствует station_route)
  #
  # Теперь мы сможем вызвать в контроллере на объекте @railway_station метод update_position
  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  # метод будет возвращать нужную нам позицию, а в качестве параметра - объект маршрута,
  # потому что в разных маршрутах позиция может быть разная
  # метод try вызывает переданный в качестве символа метод, если объект,
  # на котором вызывается try, существует(не nil) - элегантная замена if station_route
  def position_in(route)
    station_route(route).try(:position)
  end

  protected

  # мы перенесли дублирующий элемент кода в отдельный метод
  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[show edit update destroy update_position]

  # GET /railway_stations or /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1 or /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations or /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to railway_station_url(@railway_station), notice: "Railway station was successfully created." }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1 or /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to railway_station_url(@railway_station), notice: "Railway station was successfully updated." }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1 or /railway_stations/1.json
  def destroy
    @railway_station.destroy

    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: "Railway station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_position
    # находим маршрут, в рамках которого обновляем позицию благодря полю :route_id,
    # прописанному в app/views/routes/show.html.erb
    @route = Route.find(params[:route_id])
    # в параметры передаем объект маршрута -  @route, params[:position] - значение позиции.
    # не нужно передавать все параметры, необходимо передавать только то, что нужно для работы метода
    @railway_station.update_position(@route, params[:position])

    redirect_to @route
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/railway_stations/_form.html.erb
<%= form_with(model: resource) do |form| %>
 <%= render 'common/errors', resource: @railway_station %>

  <div>
    <%= form.label 'Название', style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit 'Создать' %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Показать', railway_station %></td>
  <td><%= link_to 'Изменить', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Удалить', railway_station, data: {
      turbo_method: :delete,
      turbo_confirm: 'Вы уверены?'
  } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing railway station</h1>

<%= render "form", resource: @railway_station %>

<br>

<%= link_to 'Назад к станциям', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Railway stations</h1>

<table>
  <tbody><%= render @railway_stations %></tbody>
</table>


<div><br>
  <%= link_to 'На главную', welcome_index_path, method: :get %> |
  <%= link_to 'Новая станция', new_railway_station_path %>
</div>





app/views/railway_stations/new.html.erb
<h1>New railway station</h1>

<%= render "form", resource: @railway_station %>

<br>

<div>
  <%= link_to "Back to railway stations", railway_stations_path %>
</div>

app/views/railway_stations/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <strong>Станция:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p>Станция не входит ни в один маршрут</p>
<% else %>
  <p>Станция входит в следующие маршруты:</p>
  <ul>
    <% @railway_station.routes.each do |route| %>
      <li><%= route.name %></li>
    <% end %>
  </ul>
<% end %>


<div>
  <%= link_to "Изменить", edit_railway_station_path(@railway_station) %> |
  <%= link_to "Удалить", @railway_station, data: {
      turbo_method: :delete,
      turbo_confirm: 'Вы уверены?'
  } %>

  <p><%= link_to "Назад к поездам", railway_stations_path %></p>
</div>