config/routes.rb
Rails.application.routes.draw do
  # кастомный экшн у ресурса railway_stations
  # указываем, что у нас есть дополнительный экш, где перед ним
  # пишем HTTP метод, при помощи которого мы хотим обращаться к нашему экшену
  # после запятой задаем вопрос: этот экшн применяется к конкретному объекту или коллекции?
  # URL должен содержать id объекта или нет?
  # если коллекция, пишем on: :collection. если конкретный - on: :member
  #
  # здесь важно правильно указать HTTP-метод:
  # если получение данных без изменения - GET
  # создание чего-то нового или какая-то неконкретная отправка данных на сервер - POST
  # изменение - PATCH/PUT
  # удаление - DELETE
  resources :railway_stations do
    put :update_position, on: :member
  end

  resources :trains do
    # shallow: true - эта опция укажет, что родительский объект @train нужен только для
    # экшнов index, create, new. Все остальные его не требуют. Можем в этом убедиться, посмотрев
    # роутинг командой rails routes
    resources :carriages, shallow: true
  end

  resources :routes

  # когда мы пишем resource(в единственном числе), мы создаем singular resource(единственный ресурс)
  # rails routes покажет, что у singular resource в роутинге нет метода index, что логично -
  # - раз ресурс в одном экземпляре, значит нет списка этих ресурсов
  #
  # У любого ресурса можно указать, какие экшны нам нужны - опция only для определенных экшнов,
  # опция except - все, кроме.
  resource :search, only: %i[new show edit]

  get 'welcome/index'
  get "/trains", to: "trains#index"
  get "/trains/:id", to: "trains#show"

  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  validate :station_count # кастомная валидация

  # Collbacks - механизм выполнения пользовательского кода
  # при выполнении операций над объектом
  #
  # "Хуки"(методы), которые вызываются в жизненном цикле объекта
  before_validation :set_name

  # методы private не предназначены для прямого вызва - не являются
  # частью публичного интерфейса
  private

  def set_name
    # присваиваем атрибуту name первую и последнюю станцию маршрута
    self.name ||= "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def station_count
    if railway_stations.size < 2
      # все ошибки валидации хранятся во внутреннем объекте errors, так же
      # мы можем в него добавить ошибки вызвав .add и 2 параметра(1 - поле, к которому добавляем ошибку,
      # 2 - сообщение об ошибке )
      # в интерфейсе используется railway_station_ids, можно добавить ошибку на него, либо
      # на весь объект целиком, написав :base,
      # что здесь более логично - у нас маршрут должен содержать 2 станции.
      errors.add(:base, 'Route should contain at least 2 stations')
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  # метод, который мы выполняем до того, как выполним перечисленные методы в [....]
  # указываем опцию only: и массив символов, в котором указаны те экшены, перед
  # которыми будет выполняться метод set_train
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route, notice: "Маршрут успешно создан."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @route.update(route_params)
      # redirect_to - создание нового запроса. Важно помнить: при каждом запросе создается новый объект
      # контроллера, как и инстанс-переменные.
      # Новый запрос - новые данные в объектах
      redirect_to @route, notice: "Маршрут успешно изменен."
    else
      # render - рендеринг шаблона из вида на основе тех данных, которые есть в экшне
      # в случае ошибок мы делаем рендер edit, поскольку хотим отобразить наши ошибки в рамках
      # состояния текущих объектов. Если бы не было render :edit, то контроллер по умолчанию начал искать
      # шаблон с текущем именем экшна - update
      render :edit
    end
  end

  def destroy
    @route.destroy

    redirect_to routes_path, status: :see_other
  end

  private

  # в params используется хэш с indifferent(безразличный) access
  # можно писать в названии ключа как символ params[:id], так и строку params['id']
  def set_route
    @route = Route.find(params[:id])
  end

  # ко всему объему параметров в params мы применяем require(:route) - требуем определенный ключ
  # указываем какие во внутреннем хэше route могут быть поля: permit(:name, railway_station_ids: [])
  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/routes/_form.html.erb
<%= form_with(model: resource) do |form| %>
  <%= render 'common/errors', resource: @route %>

  <div>
    <%= form.label 'Название', style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :railway_station_ids, "Список станций" %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div>
    <%= form.submit "#{ @route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Показать', route %></td>
  <td><%= link_to 'Изменить', edit_route_path(route) %></td>
  <td><%= link_to 'Удалить', route, data: {
      turbo_method: :delete,
      turbo_confirm: 'Вы уверены?'
  } %></td>
</tr>

app/views/routes/edit.html.erb
<h1>Изменить маршрут</h1>

<%= render 'form', resource: @route %>

<p><%= link_to 'Назад к маршрутам', routes_path %></p>

app/views/routes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listing Routes</h1>

<table>
  <tbody><%= render @routes %></tbody>
</table>

<div><br>
  <%= link_to 'На главную', welcome_index_path, method: :get %> |
  <%= link_to 'Новый маршрут', new_route_path %>
</div>

app/views/routes/new.html.erb
<h1>Добавить маршрут</h1>

<%= render 'form', resource: @route %>

<p><%= link_to 'Назад', routes_path %></p>

app/views/routes/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.name %>
</p>

<% if @route.railway_stations.empty? %>
  Список пуст
<% else %>
  <table>
    <thead>
    <tr>
      <td>Название</td>
      <td>Позиция</td>
    </tr>
    </thead>
    <tbody>
    <!-- делаем выборку по скоупу ordered - прописан в моделе r_s -->
    <% @route.railway_stations.ordered.each do |station| %>
      <tr>
        <td><%= station.title %></td>
        <td>
          <!-- добавляем общую форму form_tag, в которой сами определяем параметры в ней
           и как с ними работать.
           form_tag создает форму без привязки к конкретному объекту.
           Первым параметром он принимает URL - куда отправлять.
           Раз у нас экшн update_position вызывается у конкретного объекта, мы должны в параметры
            URL передать этот объект, для которого должна быть форма, чтобы подставился id.
            По умолчанию form_tag - это отправка методом POST, а наш экшн требует метод PATCH,
            поэтому нужно в явном виде указать метод PATCH. Rails 7.0.3 требует писать :put.
            form_tag не предоставляет хэлперов формы, как в form_for, типа |f| do 'f.title' end
            Раз форма не связана ни с каким объектом, то и поле не связано ни с каким атрибутом -->
          <%= form_tag update_position_railway_station_path(station), method: :put do  %>
            <!-- В :position, ... нужно передать значение этого поля, однако поле находится
             в промежуточной модели, но мы не должны напрямую обращаться к промежуточным моделям,
             нужно это как можно сильнее скрывать за реальными объектами, поэтому напишем
             метод position_in в модели r_s -->
            <%= number_field_tag :position, station.position_in(@route) %>
            <!-- Кроме позиции нам нужно передать id маршрута, поскольку если мы передадим только позицию,
             то непонятно в каком маршруте нам нужно обновлять эту позицию, вторым параметром @route.id будет
             значение первого параметра. Подробнее в r_s controller, метод update_position.
             hidden_field_tag скроет его от пользователя, поскольку информация @route.id не для изменения:
             тег будет присутсовать в HTML форме, но не будет виден пользователю
             -->
            <%= hidden_field_tag :route_id, @route.id %>
            <%= submit_tag 'Изменить' %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div>
  <%= link_to "Изменить", edit_route_path(@route) %> |
  <%= link_to "Удалить", @route, data: {
      turbo_method: :delete,
      turbo_confirm: 'Вы уверены?'
  } %>
</div>